feature04-ResultViewの追加
kudpig/SampleCode pull request #10
Opened 2021-05-01 12:32 UTC by kudpig

## 概要
一覧表示ボタンを押した先のViewを追加

## やったこと

- ResultViewController及びStoryboardの追加
- カスタムビューとしてResultListViewを作成

## クローン
`git clone -b feature04-ResultView https://github.com/kudpig/SampleCode.git`

2021-05-03 04:19 UTC, sakiyamaK requested changes
@kudpig コメントしました

2021-05-03 04:19 UTC, sakiyamaK commented on SampleCode/Controller/Result/ResultViewController.swift
> +class ResultViewController: UIViewController {
継承をしないクラスにはカプセル化の観点からfinalをつけましょう

2021-05-03 04:19 UTC, sakiyamaK commented on SampleCode/Controller/Result/ResultViewController.swift
> +class ResultViewController: UIViewController {
ResultViewControllerでは何の結果か分からないので具体性のある名前にしましょう

2021-05-03 04:19 UTC, sakiyamaK commented on SampleCode/Controller/Result/ResultViewController.swift
> +            resultStackView.spacing = 2
ここは人によるところで修正しなくてもいいですが、何をStoryboardで設定して何をコードで設定するのか明確なルールは自分の中でもっていてください
そしてそのルールをチーム開発で徹底できるように他人に説明できるようにしてください

2021-05-03 04:19 UTC, sakiyamaK commented on SampleCode/Controller/Result/ResultViewController.swift
> +    }
getしかないcomputed propertyはgetを省略できます
さらにクロージャの引数などもがっつり省略して書いたらこうなります

```
    private var calculateItemPrice: Int {
      receiveItems.filter { !$0.name.isEmpty }.map { $0.price }.reduce(0) { $0 + $1 }
    }
```

2021-05-03 04:19 UTC, sakiyamaK commented on SampleCode/View/ResultListView/ResultListView.swift
> +        priceLabel.setContentHuggingPriority(UILayoutPriority(1000), for: .horizontal)
もう基本はソースコードでパラメータ設定するという思想でいくって感じですかね？
良い悪いではなく、設計方針の確認です

2021-05-04 10:01 UTC, kudpig commented on SampleCode/Controller/Result/ResultViewController.swift
> +class ResultViewController: UIViewController {
ConfirmSelectedItemsという名称に変更しました。
`ConfirmSelectedItemsViewController`と長すぎる気もするのですが、よくあることなのでしょうか？

2021-05-04 10:09 UTC, kudpig commented on SampleCode/Controller/Result/ResultViewController.swift
> +class ResultViewController: UIViewController {
修正しました！
finalやprivateは忘れがちなので注意します。

2021-05-04 10:15 UTC, kudpig commented on SampleCode/Controller/Result/ResultViewController.swift
> +    }
見本の形に変更しました！
配列操作や`$0`の省略記法の理解が甘いので、これを機に復習します。

2021-05-04 10:46 UTC, kudpig commented on SampleCode/Controller/Result/ResultViewController.swift
> +            resultStackView.spacing = 2
大半をstoryboardで設定する仕様に変更しました！

この部分についてなんですが、元々枠線をつけるのに試行錯誤していて、StackView自体に付けたり中身のContentsに付けたり色々試すのに切り貼りしやすいようにコードで書いてたのがそのままになってました。

2021-05-04 10:49 UTC, kudpig commented on SampleCode/Controller/Result/ResultViewController.swift
> +            resultStackView.spacing = 2
１箇所、`layer.borderColor`のみコードにしています。
User Defined Runtime Attributesで設定したのですが、どうもうまく反映できませんでした。
おそらくcgcolorに出来ていないのが原因と考えられるのですが、解決できていません。

2021-05-04 10:55 UTC, kudpig commented on SampleCode/View/ResultListView/ResultListView.swift
> +        priceLabel.setContentHuggingPriority(UILayoutPriority(1000), for: .horizontal)
設計方針といったことをまっっったく考えていませんでした。
これは反省ですね・・・
何となく後々忘れそうで、コメントアウトでメモ残すためにコードで書いただけという感じでした。

他のファイルに合わせてstoryboardで設定する仕様に修正しました。

2021-05-04 11:04 UTC, kudpig commented
@sakiyamaK コメントしました！
今回の指摘はいかに今までテキトーに設計していたというのが身に染みました汗
設計方針を考えるという発想自体が無かったので、とてもよい学びになりました。

2021-05-04 13:29 UTC, sakiyamaK commented on SampleCode/Controller/Result/ResultViewController.swift
> +class ResultViewController: UIViewController {
まぁそこは永遠の課題ですね、具体的にすると長くなるし短いと仕様追加があったときに被ったりするし。

例えばユーザを検索する機能があったとして検索結果の画面を `SearchResultViewController` にしたとします
仕様追加でツイートも検索できるようにしようとなったら `SearchResultViewController`と名前が被るので `SearchResultTweetViewController` とかになりますね。
それ以外にも検索する機能がどんどん追加されていったら
`SearchResultHogeHogeViewController`, `SearchResultFugaFugaViewController` などどんどん増えますが、そうすると最初のユーザ検索の結果が `SearchResultViewController` って名前だと「何の検索結果だよ！」となります
最初から`SearchResultUserViewController`にしておけば具体的で被りません

2021-05-04 13:33 UTC, sakiyamaK commented on SampleCode/Controller/Result/ResultViewController.swift
> +            resultStackView.spacing = 2
cgColorは確か設定ができなかったかな？やり方はあったかもしれませんがちょっと忘れました
というのもcgXXXはCoreGraphicsというフレームワークの接頭辞でiOS SDKよりもっと低レイヤの技術で、MacOSにも使われてます
UIKitのUIColorは中でCoreGraphicsの機能を呼び出しています
ただStoryboardはUIKitのサポートツールなので、それより低いレイヤのCoreGraphicsのことまで知らないので設定できなかったりします(やり方はあったような気もしつつ...)

2021-05-04 13:39 UTC, sakiyamaK approved these changes
@kudpig コメントはつけましたが基本はLGTMです！！！！
![寿司ゆき:ok](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/03.png)

2021-05-04 13:39 UTC, sakiyamaK commented on SampleCode/View/ResultListView/ResultListView.swift
> +    static var identifier: String { String(describing: ResultListView.self) }
指摘忘れましたがおそらくこれってあちこちのクラスでも同じように使うのでいっそ

```
extension NSObject {
  static var identifier: String { String(describing: Self.self) }
}
```

というextensionを用意してもいいかもしれません
NSObjectはあらゆるクラスで継承されてますので、これであらゆるクラスでidentifierが使えます

2021-05-04 23:44 UTC, kudpig commented on SampleCode/Controller/Result/ResultViewController.swift
> +class ResultViewController: UIViewController {
なるほど・・・
命名はけっこう苦手（というか引き出しが少ない）ので参考になります！ありがとうございます。

2021-05-04 23:47 UTC, kudpig commented on SampleCode/View/ResultListView/ResultListView.swift
> +    static var identifier: String { String(describing: ResultListView.self) }
なるほど。やってみます！

2021-05-06 10:02 UTC, merged