feature02-Viewの更新処理の追加
kudpig/SampleCode pull request #8
Opened 2021-04-20 16:14 UTC by kudpig

## 概要
HomeViewに設置されている5th~8thのボタン(CustomView)について値の更新処理を追加する

2021-04-22 10:18 UTC, sakiyamaK commented
差分と関係ないところですが

```
    @IBOutlet weak var firstItemView: UIView! {
        didSet {
            createItemView(firstItemView, 40, .white)
        }
    }

...
```
というのがずらずら並んで見づらいですね
これらを入れてるstackviewをIBOutletでつないで

```
@IBOutlet weak var itemsStackView: UIStackView! {
  didSet {
              itemsStackView.arrangedSubviews.forEach {
            createItemView($0, 4, .white)
          }
  }
}
```
とすればいいですね

2021-04-22 10:48 UTC, sakiyamaK requested changes

2021-04-22 10:48 UTC, sakiyamaK commented on SampleCode/View/CustomView/ButtonView.swift
>      func update(number: String) {
numberという名前でString型はさすがに気持ち悪いですね

```
func update(number: Int) {
numberLabel.text = number.description
...
}
```

ぐらいにしましょう

2021-04-22 13:39 UTC, sakiyamaK requested changes
@kudpig コメントしました

2021-04-22 13:39 UTC, sakiyamaK commented on SampleCode/Controller/Home/HomeViewController.swift
> +    private lazy var selectItems = [Item](repeating: Item.createEmpty(), count: 8)
8とか4とかマジックナンバーが多すぎです。
この数値を見た時に何を意味する８なのか全然分からないことが問題です。
せめて定数化して意味つけしてください

```
let numberOfButton = 8
private lazy var selectItems = [Item](repeating: Item.createEmpty(), count: numberOfButton)
```

ただし、今回の場合はenumを利用します。

まず `CaseIterable` に準拠させるとallCasesというパラメータが使えるようになり,enumの全パターンが配列で得られます
```
enum HogeHoge: CaseIterable {
  case a, b, c
}

HogeHoge.allCases //enumの全パターンの配列が得られる [HogeHoge.a, HogeHoge.b, HogeHoge.c]

```

次にcaseの初期値だけ設定すればあとは2,3,4...と設定されます
```
enum FugaFuga: Int {
  case a = 1, b, c
}
```

これを踏まえたうえで

```
enum WhichBtn: Int, CaseIterable {
  case first = 0, second, third, fourth, fifth, sixth, seventh, eighth, none
}

private lazy var selectItems = [Item](repeating: Item.createEmpty(), count: WhichBtn.allCases.count)


//いろいろ4と書いてるところ
let numberIndex = numbers[index - WhichBtn.fifth.rawValue]
```

2021-04-22 13:39 UTC, sakiyamaK commented on SampleCode/Controller/Home/HomeViewController.swift
> +            }
このメソッドが本来やりたい処理のスコープを深くするのはやめましょう
スコープとは`{` から `}`  までのことで入れ子になるほどスコープ深いといいます

```
func hogehoge() {
  //浅い
  if hoge {
    //ひとつ深い
   if higehige {
      //ふたつ深い
   }
  }
}
```

なので

```
func method () {
  if hogehoge {
      //このメソッドが本来やりたいこと
  }
}
```

ではなく

```
func method () {
  guard hogehoge else { return }
  //このメソッドが本来やりたいこと
}
```

2021-04-23 18:04 UTC, kudpig commented
一番目のコメントの

>差分と関係ないところですが
    @IBOutlet weak var firstItemView: UIView! { 以下省略
というのがずらずら並んで見づらいですね

の部分に関して、１度指摘の通りforEachを使用した形に書き換えました。

その上で、outletで繋ぐやり方とコードで生成するやり方が混在してしまっているのは
余りにも見にくい（汚い？）ため大部分を削除し、コードで書くやり方に統一しました。

無かったことにはなりましたが、didSetの中身をforEachで回すやり方はとても勉強になりました。

2021-04-23 19:32 UTC, kudpig commented on SampleCode/Controller/Home/HomeViewController.swift
> +            }
> このメソッドが本来やりたい処理のスコープを深くするのはやめましょう

つい`if`を使ってしまいがちなので、なるべく`guard`を使用して浅く済ませるように意識します！

2021-04-23 20:00 UTC, kudpig commented on SampleCode/Controller/Home/HomeViewController.swift
> +    private lazy var selectItems = [Item](repeating: Item.createEmpty(), count: 8)
マジックナンバーについて修正しました。

上記見本では`WhichBtn.allCases.count`で値を取得していますが、以下の問題が生じたため手法を変えて実装しました。

- `WhichBtn`は何も押されていないという状態を表す`case .none`を持っており、生成したいItemインスタンスの数と一致しなくなる

なので `StackViewに生成されるViewの数` = `Itemインスタンスの数` と考え、
titles.countとしました。

その他8やら4やら書いているところも修正しました。

(結果的にCaseIterableは使用しない形になってしまいましたが、enum型はとりあえずCaseIterableを準拠させとくものなのでしょうか？)

2021-04-23 20:09 UTC, kudpig commented
Titleデータが文字列べた打ちだったので
Modelに切り離しました。

2021-04-24 05:22 UTC, sakiyamaK reviewed
@kudpig LGTMですね！！！
![エンジニアを褒めるネコ:さすがです](https://raw.githubusercontent.com/fukayatsu/lttm-crx/master/vendor/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%82%92%E8%A4%92%E3%82%81%E3%82%8B%E3%83%8D%E3%82%B3/04_%E3%81%95%E3%81%99%E3%81%8C%E3%81%A7%E3%81%99.png)

2021-04-24 05:22 UTC, sakiyamaK approved these changes

2021-04-24 06:10 UTC, merged