feature03-フィルター機能追加とResult画面の実装
kudpig/SampleCode pull request #9
Opened 2021-04-30 07:56 UTC by kudpig

## 概要
以下の２つの機能を実装した

- TableViewのフィルター機能
- Result画面

2021-05-03 03:58 UTC, sakiyamaK requested changes
@kudpig コメントしました、だいぶまとまってますね

2021-05-03 03:58 UTC, sakiyamaK commented on SampleCode/Controller/ListTable/ListTableViewController.swift
> +    private lazy var displayItemList = itemList
いちいちメモリに代入し直す必要はなさそうですね

```
    @objc private func handleSegmentChage() {
      tableView.reloadData()
    }

    private lazy var itemList = Item.createDefaultItems()
    
    private var displayItemList: [Item] {
      guard segmentControl.selectedSegmentIndex != .zero else {
        return itemList
      }
      return itemList.filter { $0.type == Item.genre.allCases[segmentControl.selectedSegmentIndex] }
    }

```

2021-05-03 03:58 UTC, sakiyamaK commented on SampleCode/Controller/ListTable/ListTableViewController.swift
>  extension ListTableViewController: UITableViewDelegate, UITableViewDataSource {
protocolに準拠する処理はなるべるextensionを分けましょう

```
extension ListTableViewController: UITableViewDelegate {
}

extension ListTableViewController: UITableViewDataSource {
}
```

2021-05-04 08:32 UTC, kudpig commented
> @kudpig コメントしました、だいぶまとまってますね

ありがとうございます！ハードコードを減らすということと、前回のレビューで学んだマジックナンバーを使わないということを意識しました！

2021-05-04 08:34 UTC, kudpig commented on SampleCode/Controller/ListTable/ListTableViewController.swift
> +    private lazy var displayItemList = itemList
修正しました！
見本のようにgetterで値を取得すると、関数の中身もすっきりして見やすいですね！

2021-05-04 08:36 UTC, kudpig commented on SampleCode/Controller/ListTable/ListTableViewController.swift
>  extension ListTableViewController: UITableViewDelegate, UITableViewDataSource {
修正しました！

2021-05-04 08:37 UTC, kudpig commented
@sakiyamaK 
コメント&修正しました！

2021-05-04 09:42 UTC, sakiyamaK reviewed
@kudpig LGTMですね！！
![エンジニアを褒めるネコ:コードがきれい！](https://raw.githubusercontent.com/fukayatsu/lttm-crx/master/vendor/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%82%92%E8%A4%92%E3%82%81%E3%82%8B%E3%83%8D%E3%82%B3/02_%E3%82%B3%E3%83%BC%E3%83%89%E3%81%8C%E3%81%8D%E3%82%8C%E3%81%84%EF%BC%81.png)

2021-05-04 09:43 UTC, sakiyamaK approved these changes

2021-05-06 10:02 UTC, merged